version: '3.8'

services:
  expo_app:
    container_name: survivor_expo
    build: ./app
    tty: true
    networks:
      - api

  survivor_api:
    container_name: survivor_api
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - survivor_db
    networks:
      - api
      - database

  survivor_db:
    container_name: survivor_db
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survivor_app
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - database

networks:
  database:
  api:
