env:
  browser: true
  es2022: true

extends:
  - plugin:react/recommended
  - prettier

parser: "@typescript-eslint/parser"

parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module

settings:
  react:
    version: "detect"

rules:
  no-plusplus: [ "error", { "allowForLoopAfterthoughts": true } ]

  react/react-in-jsx-scope: off
  react/no-unescaped-entities: off
